### PR TITLE
Added compatibility with React 0.14

### PR DESCRIPTION
**Pull request by dallonf**
In React 0.14, refs to a DOM node will return the node itself. Calling
getDOMNode() on it works, but throws a loud warning. See the [announcement blog post](https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html#dom-node-refs)

### CODE REVIEW

**Comment by mhuggins** [comment]
Thanks for the PR.  It seems like it might just be worth using `React.findDOMNode` instead.

**Comment by mhuggins** [comment]
In other words:

```javascript
var target = React.findDOMNode(this.refs.loader);
```

I think that a conditional wouldn't be needed then.

**Comment by dallonf** [comment]
Ah, you're right, `findDOMNode` doesn't throw warnings when used on a DOM Node. This would also make it compatible with ES6 class components. It might break compatibility with React 0.12, though (I think findDOMNode was added in 0.13) - if anybody's still using that?

The bigger issue is that `React.findDOMNode` is deprecated in 0.14 - you've got to use `ReactDOM.findDOMNode` instead or it throws an equally loud warning. Not sure how to handle that in a way that doesn't break in 0.13.

**Comment by mhuggins** [comment]
Ahh, I didn't realize that `React.findDOMNode` was deprecated as well.  Seems like it could just be a simple check then, i.e.:

```javascript
var dom = typeof(ReactDOM) !== 'undefined' ? ReactDOM : React;
var target = dom.findDOMNode(this.refs.loader)
```

**Comment by mhuggins** [comment]
I'm also okay with just using ReactDOM altogether, bumping the minor version, and updating the readme to instruct users of React 0.13- to use the previous version.

**Comment by dallonf** [comment]
Some projects are currently publishing to npm under a `-react-pre` tag (like [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap#react-014) to deal with this since React 0.14 isn't official yet. Your call! :smile: Maybe it's simpler for me to just use my fork until React 0.14 has a final release.

**Comment by adjohnson916** [comment]
+1 Who's the prospective merger here? Aren't these changes backwards compatible without `React.findDOMNode` or `ReactDOM.findDOMNode`? Would you consider merging this and bumping to `2.x.x` or `1.x.x-react-pre` or anything to get this released officially in some form?

**Comment by mhuggins** [comment]
Someone at @quickleft will need to make and/or approve of these changes.  I created the package, but I no longer have owner or contributor rights.

**Comment by dallonf** [comment]
Since React 0.14 is out, we can just use `ReactDOM.findDOMNode` and bump the semver as a breaking change. Lemme make those edits now...

**Comment by nonsensery** [comment]
@dallonf This looks great – thanks for putting it together! I'll make a follow up PR to update the Read Me and bump the version.

**Comment by mhuggins** [comment]
Thanks @nonsensery!

**Pull request merged**
