### PR TITLE
Add className prop for loaded content

### PR DESCRIPTION
**Pull request by willdurand**

### CODE REVIEW

**Comment by mikekauffman** [comment]
Thanks for this, @willdurand. Can you please add a test and update the readme?

**Comment by willdurand** [comment]
Of course I can :heart:

**Comment by willdurand** [comment]
Updated: doc + test

**Comment by willdurand** [comment]
@mikekauffman thanks for having merged this PR. May I ask you when to expect a new tag/release?

**Comment by mikekauffman** [comment]
I've released 2.1.0 with your changes. You should be able to pull/update from npm.

**Comment by willdurand** [comment]
Awesome, thank you very much!

**Pull request merged**
